<?php
/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
 */

function fibonacci($a, $b){
    $c = 0;
    $array = [1, 2];
    $arrayPair = [];
    while($c < 3500000){
        $c = $a + $b;
        $a = $b;
        $b = $c;
        $array[] = $c;
    }
    foreach ($array as $value){
        if($value % 2 == 0){
            $arrayPair[] = $value;
        }
    }
    echo array_sum($arrayPair);
}

fibonacci(1, 2);

// 4613732